name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
        working-directory: .
        
      - name: Run tests
        run: |
          pytest test_game.py
        working-directory: tests

      - name: Build Docker image
        run: docker build -t snake-game .
        working-directory: .
